### PR TITLE
Port some new API from Zephyr

### LINKED ISSUE #215: [API]: Porting Zephyr Astarte data types

### LINKED ISSUE #220: [API] Port pairing utilities from Zephyr SDK

### LINKED ISSUE #221: [API] Port Zephyr SDK result types

### LINKED ISSUE #222: [API] Port Zephyr SDK device ID generation
This SDK referred to the device ID as a hardware ID. This is incorrect as the device ID is not always hardware ID related.

### PR DESCRIPTION
**Pull request by sorru94**

### CODE REVIEW

File: include/astarte_device_sdk/astarte.h [hunk 1]
```diff
@@ -4,8 +4,8 @@
  * SPDX-License-Identifier: Apache-2.0
  */
 
-#ifndef ASTARTE_DEVICE_SDK_ASTARTE_H
-#define ASTARTE_DEVICE_SDK_ASTARTE_H
+#ifndef _ASTARTE_DEVICE_SDK_ASTARTE_H_
```
Comment (harlem88) [inline include/astarte_device_sdk/astarte.h]: Why do you add an `_` before each Header guard?

File: private/bson_serializer.h [hunk 2]
```diff
@@ -23,7 +23,7 @@ typedef struct
     size_t size;
     /** @brief Byte array containing the serialized data. */
     uint8_t *buf;
-} astarte_bson_serializer_t;
+} new_ast_bson_serializer_t;
```
Comment (harlem88) [inline private/bson_serializer.h:26]: Why do you add `new` prefix to some functions and struct?

File: private/http.h [hunk 3]
```diff
@@ -31,8 +33,8 @@ extern "C" {
  * @param[in] resp_buf_size Size of the response output buffer.
  * @return ASTARTE_RESULT_OK if successful, otherwise an error code.
  */
-astarte_result_t astarte_http_post(int32_t timeout_ms, const char *url, const char **header_fields,
-    const char *payload, uint8_t *resp_buf, size_t resp_buf_size);
+astarte_result_t astarte_http_post(const char *host, const char *path, const char *auth_bearer,
```
Comment (harlem88) [inline private/http.h:34]: Since you changed the params and params name, I believe you have to change also the method documentation.

File: private/http.h [hunk 4]
```diff
@@ -45,8 +47,8 @@ astarte_result_t astarte_http_post(int32_t timeout_ms, const char *url, const ch
  * @param[in] resp_buf_size Size of the response output buffer.
  * @return ASTARTE_RESULT_OK if successful, otherwise an error code.
  */
-astarte_result_t astarte_http_get(int32_t timeout_ms, const char *url, const char **header_fields,
-    uint8_t *resp_buf, size_t resp_buf_size);
+astarte_result_t astarte_http_get(const char *host, const char *path, const char *auth_bearer,
```
Comment (harlem88) [inline private/http.h:46]: same above

File: private/pairing_private.h [hunk 5]
```diff
@@ -62,7 +59,7 @@ astarte_result_t astarte_pairing_get_mqtt_broker_hostname_and_port(int32_t http_
  * @param[out] client_crt Client private key and certificate for mutual TLS authentication.
  * @return ASTARTE_RESULT_OK if successful, otherwise an error code.
  */
-astarte_result_t astarte_pairing_get_client_certificate(int32_t timeout_ms, const char *device_id,
+astarte_result_t new_ast_pairing_get_client_certificate(const char *device_id,
```
Comment (harlem88) [inline private/pairing_private.h]: Remove `timeout_ms` param from doc.

File: private/pairing_private.h [hunk 6]
```diff
@@ -76,11 +73,11 @@ astarte_result_t astarte_pairing_get_client_certificate(int32_t timeout_ms, cons
  * @param[in] crt_pem Input buffer containing the PEM certificate to verify.
  * @return ASTARTE_RESULT_OK if successful, otherwise an error code.
  */
-astarte_result_t astarte_pairing_verify_client_certificate(
-    int32_t timeout_ms, const char *device_id, const char *cred_secr, const char *crt_pem);
+astarte_result_t new_ast_pairing_verify_client_certificate(const char *device_id,
```
Comment (harlem88) [inline private/pairing_private.h]: same above

File: src/pairing.c [hunk 7]
```diff
@@ -143,7 +67,8 @@ static astarte_result_t encode_register_device_payload(
  * @return ASTARTE_RESULT_OK if successful, otherwise an error code.
  */
 static astarte_result_t parse_register_device_response(
-    char *resp_buf, char *out_cred_secr, size_t out_cred_secr_size);
+    const char response[ASTARTE_HTTP_OUTPUT_BUFFER_LEN + 1],
```
Comment (harlem88) [inline src/pairing.c:69]: It seems the method documentation differs from new params name definition.

File: src/pairing.c [hunk 8]
```diff
@@ -154,633 +79,312 @@ static astarte_result_t parse_register_device_response(
...
- * @brief Encode the payload for the get client certificate HTTP request.
- *
- * @param[in] csr Certificate signing request to be encoded in the payload.
- * @param[out] out_buff Buffer where to store the encoded payload.
- * @param[in] out_buff_size Size of the output buffer.
- * @return ASTARTE_RESULT_OK if successful, otherwise an error code.
- */
-static astarte_result_t encode_get_client_certificate_payload(
-    const char *csr, char *out_buff, size_t out_buff_size);
+    const char response[ASTARTE_HTTP_OUTPUT_BUFFER_LEN + 1],
```
Comment (harlem88) [inline src/pairing.c:79]: same above

File: src/pairing.c [hunk 9]
```diff
@@ -154,633 +79,312 @@ static astarte_result_t parse_register_device_response(
...
- * @brief Encode the payload for the verify client certificate HTTP request.
- *
- * @param[in] crt_pem Certificate to be encoded in the payload.
- * @param[out] out_buff Buffer where to store the encoded payload.
- * @param[in] out_buff_size Size of the output buffer.
- * @return ASTARTE_RESULT_OK if successful, otherwise an error code.
- */
-static astarte_result_t encode_verify_client_certificate_payload(
-    const char *crt_pem, char *out_buff, size_t out_buff_size);
+    const char response[ASTARTE_HTTP_OUTPUT_BUFFER_LEN + 1],
```
Comment (harlem88) [inline src/pairing.c:89]: same above

**Review by harlem88 — CHANGES_REQUESTED** [review]

File: include/astarte_device_sdk/astarte.h (hunk 1 above)
Comment (sorru94) [reply include/astarte_device_sdk/astarte.h]: To stay in line with this library's older header guards. 
I would personally remove the `_`.

File: private/bson_serializer.h (hunk 2 above)
Comment (sorru94) [reply private/bson_serializer.h:26]: It is a temporary renaming to avoid conflicts with the old definitions of structures and functions.
I would progressively remove the old ones.

File: private/pairing_private.h [hunk 10]
```diff
@@ -16,7 +16,7 @@
 #include "astarte_device_sdk/result.h"
 
 #include "crypto.h"
-#include "mqtt.h"
+// #include "mqtt.h"
```
Comment (harlem88) [inline private/pairing_private.h]: Did you comment it to add it later?

File: include/astarte_device_sdk/device_id.h [hunk 11]
```diff
@@ -0,0 +1,74 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline include/astarte_device_sdk/device_id.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: include/astarte_device_sdk/interface.h [hunk 12]
```diff
@@ -0,0 +1,102 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline include/astarte_device_sdk/interface.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: include/astarte_device_sdk/mapping.h [hunk 13]
```diff
@@ -0,0 +1,114 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline include/astarte_device_sdk/mapping.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: include/astarte_device_sdk/object.h [hunk 14]
```diff
@@ -0,0 +1,79 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline include/astarte_device_sdk/object.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: include/astarte_device_sdk/pairing.h [hunk 15]
```diff
@@ -0,0 +1,54 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline include/astarte_device_sdk/pairing.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: include/astarte_device_sdk/result.h [hunk 16]
```diff
@@ -0,0 +1,131 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline include/astarte_device_sdk/result.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: include/astarte_device_sdk/util.h [hunk 17]
```diff
@@ -0,0 +1,39 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline include/astarte_device_sdk/util.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: private/bson_deserializer.h [hunk 18]
```diff
@@ -0,0 +1,199 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline private/bson_deserializer.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: private/bson_serializer.h [hunk 19]
```diff
@@ -0,0 +1,281 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline private/bson_serializer.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: private/bson_types.h [hunk 20]
```diff
@@ -0,0 +1,41 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline private/bson_types.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: private/crypto.h [hunk 21]
```diff
@@ -0,0 +1,65 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline private/crypto.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: private/data_validation.h [hunk 22]
```diff
@@ -0,0 +1,77 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline private/data_validation.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: private/http.h [hunk 23]
```diff
@@ -0,0 +1,53 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline private/http.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: private/individual_private.h [hunk 24]
```diff
@@ -0,0 +1,72 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline private/individual_private.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: private/interface_private.h [hunk 25]
```diff
@@ -0,0 +1,76 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline private/interface_private.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: private/mapping_private.h [hunk 26]
```diff
@@ -0,0 +1,58 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline private/mapping_private.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: private/object_private.h [hunk 27]
```diff
@@ -0,0 +1,75 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline private/object_private.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: private/pairing_private.h [hunk 28]
```diff
@@ -0,0 +1,76 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline private/pairing_private.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: private/tls_credentials.h [hunk 29]
```diff
@@ -0,0 +1,33 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline private/tls_credentials.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: private/uuid.h [hunk 30]
```diff
@@ -0,0 +1,124 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline private/uuid.h]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: python_scripts/generate_interfaces.py [hunk 31]
```diff
@@ -0,0 +1,256 @@
+# (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline python_scripts/generate_interfaces.py]:
```suggestion
# (C) Copyright 2024-2025, SECO Mind Srl
```

File: src/bson_deserializer.c [hunk 32]
```diff
@@ -0,0 +1,329 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline src/bson_deserializer.c]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: src/result.c [hunk 33]
```diff
@@ -0,0 +1,76 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline src/result.c]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: src/bson_serializer.c [hunk 34]
```diff
@@ -0,0 +1,341 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline src/bson_serializer.c]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: src/crypto.c [hunk 35]
```diff
@@ -0,0 +1,199 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline src/crypto.c]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: src/data_validation.c [hunk 36]
```diff
@@ -0,0 +1,120 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline src/data_validation.c]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: src/device_id.c [hunk 37]
```diff
@@ -0,0 +1,39 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline src/device_id.c]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: src/http.c [hunk 38]
```diff
@@ -0,0 +1,241 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline src/http.c]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: src/individual.c [hunk 39]
```diff
@@ -0,0 +1,982 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline src/individual.c]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: src/interface.c [hunk 40]
```diff
@@ -0,0 +1,105 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline src/interface.c]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: src/mapping.c [hunk 41]
```diff
@@ -0,0 +1,185 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline src/mapping.c]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: src/object.c [hunk 42]
```diff
@@ -0,0 +1,144 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline src/object.c]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

File: src/pairing.c [hunk 43]
```diff
@@ -0,0 +1,390 @@
+/*
+ * (C) Copyright 2024, SECO Mind Srl
```
Comment (harlem88) [inline src/pairing.c]:
```suggestion
 * (C) Copyright 2024-2025, SECO Mind Srl
```

**Review by harlem88 — CHANGES_REQUESTED** [review]
LGTM, Please verify only the Copyright year in the new file

File: private/pairing_private.h (hunk 10 above)
Comment (sorru94) [reply private/pairing_private.h]: No, just forgotten

File: include/astarte_uuid.h [hunk 44]
```diff
@@ -52,18 +53,18 @@ astarte_err_t uuid_to_string(const uuid_t uuid, char *out);
...
  */
-void uuid_generate_v4(uuid_t out);
+void astarte_uuid_generate_v4(astarte_uuid_t out);
 
 #ifdef __cplusplus
 }
 #endif
 
-#endif // _UUID_H_
+#endif // _ASTARTE_UUID_H_
```
Comment (harlem88) [inline include/astarte_uuid.h]:
```suggestion
#endif // ASTARTE_UUID_H_
```

File: include/astarte_uuid.h [hunk 45]
```diff
@@ -4,17 +4,17 @@
  * SPDX-License-Identifier: LGPL-2.1-or-later OR Apache-2.0
  */
 
-#ifndef _UUID_H_
-#define _UUID_H_
+#ifndef _ASTARTE_UUID_H_
+#define _ASTARTE_UUID_H_
```
Comment (harlem88) [inline include/astarte_uuid.h]:
```suggestion
#ifndef ASTARTE_UUID_H_
#define ASTARTE_UUID_H_
```

**Review by harlem88 — CHANGES_REQUESTED** [review]

**Review by harlem88 — APPROVED** [review]
