### PR TITLE
Fix hwid generation

### LINKED ISSUE #120: Hardware ID generation with IDF v5.0
The `hwid` generated with IDF `v5.0` is different compared to the one generated from previous versions of the IDF.
The issue spawns from the `esp_chip_info` function called in the `astarte_hwid_get_id` function.
https://github.com/astarte-platform/astarte-device-sdk-esp32/blob/18f8ca62f35da4a411cd1686371c28e1627be0cb/astarte_hwid.c#L33

The field `revision` for the type `esp_chip_info_t` has changed content in this latest version of the ESP IDF.
In the newer version of the IDF the `revision` field contains the [chip revision version](https://docs.espressif.com/projects/esp-idf/en/v5.0.1/esp32/api-reference/system/misc_system_api.html#_CPPv415esp_chip_info_t
), in the format MXX. Where M - wafer major version, XX - wafer minor version.
In previous versions of the IDF, only the major version was contained in the `revision` field.
Check out the related sections in the [migration guide](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/5.0/system.html#esp-hw-support) for more info.

### PR DESCRIPTION
**Pull request by sorru94**
Closes #120.

### CODE REVIEW

File: astarte_hwid.c [hunk 1]
```diff
@@ -37,13 +37,18 @@ astarte_err_t astarte_hwid_get_id(uint8_t *hardware_id)
     int embedded_flash = (chip_info.features & CHIP_FEATURE_EMB_FLASH) != 0;
     int bluetooth = (chip_info.features & CHIP_FEATURE_BT) != 0;
     int ble = (chip_info.features & CHIP_FEATURE_BLE) != 0;
+#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 0, 0)
+    uint16_t revision = chip_info.revision / 100u;
+#else
+    uint16_t revision = chip_info.revision;
+#endif
```
Comment (rbino) [inline astarte_hwid.c:44]: Maybe add a comment explaining what's happening and possibly pointing to the changelog of esp-idf, because it's hard to understand why this `ifdef` is needed without any kind of context while reading the code

Comment (sorru94) [reply astarte_hwid.c:45]: I think anyone reading the macro would understand that this change relates to an update to IDF version 5.0.
But sure, adding a comment won't hurt.

**Review by harlem88 — APPROVED** [review]

**Comment by harlem88** [comment]
Add line to Changelog:

## [1.1.2] - Unreleased
### Fixed
- Fix hardware ID generation for IDF 5.0.

**Review by harlem88 — APPROVED** [review]
